// This file is auto-generated by TanStack Router
import { createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/')

const rootRoute = {
  id: '__root__',
  component: () => null,
}

export const routeTree = rootRoute
